[package]
name = "romeo-test"
version = "0.1.0"
authors = ["John Murray <me@johnmurray.io>"]
description = "--"
license = "Apache-2.0"

[dependencies]
pretty_env_logger = "0.2"

[dependencies.romeo]
path = ".."
